//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoRecepcion
    {
        public long PrestamoRecepcionId { get; set; }
        public long UsuarioId { get; set; }
        public long EquipoId { get; set; }
        public Nullable<int> FacultadId { get; set; }
        public Nullable<int> SemestreBasico { get; set; }
        public long AuxilliarPrestaId { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public bool PrestamoMaual { get; set; }
        public Nullable<long> AuxilliarRecibeId { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<bool> RecepcionManual { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Facultad Facultad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
