//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEventoGestion
    {
        public TipoEventoGestion()
        {
            this.EventoGestions = new HashSet<EventoGestion>();
        }
    
        public int TipoEventoGestionId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<EventoGestion> EventoGestions { get; set; }
    }
}
