//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEquipo
    {
        public TipoEquipo()
        {
            this.Equipoes = new HashSet<Equipo>();
            this.RestriccionTipoEquipoes = new HashSet<RestriccionTipoEquipo>();
        }
    
        public int TipoEquipoId { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Referencia { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public long CreadoId { get; set; }
        public Nullable<long> ModificadoId { get; set; }
    
        public virtual ICollection<Equipo> Equipoes { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<RestriccionTipoEquipo> RestriccionTipoEquipoes { get; set; }
    }
}
