//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Equipoes = new HashSet<Equipo>();
            this.Equipoes1 = new HashSet<Equipo>();
            this.Facultads = new HashSet<Facultad>();
            this.Facultads1 = new HashSet<Facultad>();
            this.TipoEquipoes = new HashSet<TipoEquipo>();
            this.TipoEquipoes1 = new HashSet<TipoEquipo>();
            this.Anotacions = new HashSet<Anotacion>();
            this.Anotacions1 = new HashSet<Anotacion>();
            this.Anotacions2 = new HashSet<Anotacion>();
            this.Multas = new HashSet<Multa>();
            this.Multas1 = new HashSet<Multa>();
            this.Multas2 = new HashSet<Multa>();
            this.PrestamoRecepcions = new HashSet<PrestamoRecepcion>();
            this.PrestamoRecepcions1 = new HashSet<PrestamoRecepcion>();
            this.Usuario1 = new HashSet<Usuario>();
            this.Usuario11 = new HashSet<Usuario>();
            this.Equipoes2 = new HashSet<Equipo>();
            this.Menus = new HashSet<Menu>();
            this.Menus1 = new HashSet<Menu>();
            this.Sedes = new HashSet<Sede>();
            this.Sedes1 = new HashSet<Sede>();
            this.Restriccions = new HashSet<Restriccion>();
            this.Restriccions1 = new HashSet<Restriccion>();
            this.EventoGestions = new HashSet<EventoGestion>();
        }
    
        public long UsuarioId { get; set; }
        public int TipoUsuarioId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Documento { get; set; }
        public string BarCode { get; set; }
        public byte[] Password { get; set; }
        public bool PasswordCoded { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public long CreadoId { get; set; }
        public Nullable<long> ModificadoId { get; set; }
        public Nullable<int> FacultadId { get; set; }
        public Nullable<int> SemestreBasico { get; set; }
        public byte[] Token { get; set; }
        public Nullable<System.DateTime> TokenDate { get; set; }
        public string Codigo { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ICollection<Equipo> Equipoes { get; set; }
        public virtual ICollection<Equipo> Equipoes1 { get; set; }
        public virtual ICollection<Facultad> Facultads { get; set; }
        public virtual ICollection<Facultad> Facultads1 { get; set; }
        public virtual Facultad Facultad { get; set; }
        public virtual ICollection<TipoEquipo> TipoEquipoes { get; set; }
        public virtual ICollection<TipoEquipo> TipoEquipoes1 { get; set; }
        public virtual ICollection<Anotacion> Anotacions { get; set; }
        public virtual ICollection<Anotacion> Anotacions1 { get; set; }
        public virtual ICollection<Anotacion> Anotacions2 { get; set; }
        public virtual ICollection<Multa> Multas { get; set; }
        public virtual ICollection<Multa> Multas1 { get; set; }
        public virtual ICollection<Multa> Multas2 { get; set; }
        public virtual ICollection<PrestamoRecepcion> PrestamoRecepcions { get; set; }
        public virtual ICollection<PrestamoRecepcion> PrestamoRecepcions1 { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Usuario> Usuario11 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
        public virtual ICollection<Equipo> Equipoes2 { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual ICollection<Sede> Sedes { get; set; }
        public virtual ICollection<Sede> Sedes1 { get; set; }
        public virtual ICollection<Restriccion> Restriccions { get; set; }
        public virtual ICollection<Restriccion> Restriccions1 { get; set; }
        public virtual ICollection<EventoGestion> EventoGestions { get; set; }
    }
}
