//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Historial_Estudiante
    {
        public long PrestamorecepcionId { get; set; }
        public long UsuarioId { get; set; }
        public long EquipoId { get; set; }
        public Nullable<int> TipoEquipoId { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string CodigoInventario { get; set; }
        public string CodigoLaboratorio { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
    }
}
