//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Equipo
    {
        public long EquipoId { get; set; }
        public long CreadoId { get; set; }
        public Nullable<long> ModificadoId { get; set; }
        public int TipoEquipoId { get; set; }
        public string CodigoInventario { get; set; }
        public string CodigoLaboratorio { get; set; }
        public string Serial { get; set; }
        public Nullable<long> UsuarioResponsableId { get; set; }
        public string UsuarioResponsable { get; set; }
        public string UsuarioResponsableCodigoBarras { get; set; }
        public string TipoEquipo { get; set; }
        public string Marca { get; set; }
        public string Referencia { get; set; }
        public bool Activo { get; set; }
        public string Creado { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public string Modificado { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<long> UsuarioInventarioResponsableId { get; set; }
        public string UsuarioInventarioResponsable { get; set; }
        public string UsuarioInventarioResponsableCodigoBarras { get; set; }
    }
}
