//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Menu_Reportes
    {
        public int MenuId { get; set; }
        public bool Activo { get; set; }
        public string Texto { get; set; }
        public string Imagen { get; set; }
        public string Destino { get; set; }
        public int Orden { get; set; }
        public long CreaId { get; set; }
        public string Grupo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<long> ModificaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
