//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DetallePrestamoRecepcion
    {
        public string Documento { get; set; }
        public string Codigo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Facultad { get; set; }
        public string Rol { get; set; }
        public string CodigoEquipo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> SemestreBasico { get; set; }
        public bool PrestamoMaual { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public string PrestadoPor { get; set; }
        public Nullable<bool> RecepcionManual { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string RecibidoPor { get; set; }
        public Nullable<int> FacultadId { get; set; }
        public long PrestamoRecepcionId { get; set; }
    }
}
