//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PrestamoRecepcion
    {
        public long UsuarioId { get; set; }
        public int TipoUsuarioId { get; set; }
        public string TipoUsuario { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> FacultadId { get; set; }
        public Nullable<int> SemestreBasico { get; set; }
        public Nullable<int> nAnotaciones { get; set; }
        public Nullable<int> nMultas { get; set; }
        public Nullable<int> nEquipos { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Facultad { get; set; }
        public bool Activo { get; set; }
    }
}
