//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EquiposACargo
    {
        public long UsuarioId { get; set; }
        public string CodigoLaboratorio { get; set; }
        public string TipoEquipo { get; set; }
        public long EquipoId { get; set; }
    }
}
