//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Inactivos
    {
        public long UsuarioIdInactivo { get; set; }
        public Nullable<int> Prestamos { get; set; }
        public Nullable<int> PrestamosObsoletos { get; set; }
        public Nullable<int> MultasActivas { get; set; }
        public Nullable<int> AnotacionesActivas { get; set; }
    }
}
